[[ -r "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# uv
export PATH="$HOME/.local/bin:$PATH"
# The agent harness repo's agent-runtime.toml is mise's lower-precedence system
# config, so every shell (and every agent subprocess) sees the agent-functional
# toolset while this repo's config.toml still wins on shared keys.
export MISE_SYSTEM_CONFIG_FILE="$HOME/dev/agent/agent-runtime.toml"

# Machine-local, non-public overrides (e.g. internal infra endpoints). Not
# tracked here — this dotfiles repo is public. See ~/.zshenv.local.
[[ -r "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"

# Secrets generated by `secret sync` from OpenBao (600, gitignored). Sourced
# here so non-interactive shells (agents, CI, subprocesses) get them too, not
# just interactive .zshrc. No-ops on machines where secrets were never synced.
[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets.zsh" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/secrets.zsh"
